version: 2
updates:
  - package-ecosystem: npm
    directory: /litblogs
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend
    groups:
      npm-non-major:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /litblogs
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend
    groups:
      python-non-major:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    groups:
      actions-non-major:
        update-types:
          - minor
          - patch
