BEGIN;

CREATE TABLE federated_identities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(16) NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_federated_identity_provider
        CHECK (provider IN ('google', 'microsoft')),
    CONSTRAINT uq_federated_identity_subject
        UNIQUE (provider, issuer, subject),
    CONSTRAINT uq_federated_identity_provider_user
        UNIQUE (provider, user_id),
    CONSTRAINT fk_federated_identity_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_federated_identities_user_id
    ON federated_identities (user_id);

-- Intentionally perform no automatic email-based identity backfill. Existing
-- accounts must be linked from a trusted operator migration or a future
-- authenticated account-linking flow using a verified provider subject.

COMMIT;
