const FPS = 30;
const CAPTION_INSET_FRAMES = 6;

const rawScenes = [
  {
    id: "title",
    title: "Welcome to LitBlog",
    durationInFrames: 159,
    narrationDurationInFrames: 135,
    narration: "Welcome to LitBlog. In under two minutes, you'll create an account, join a class, and publish your first post.",
    captureAsset: "captures/student-hub.jpg",
    audioAsset: "audio/title.mp3",
    camera: [
      { frame: 0, scale: 1.02, x: 0, y: 0 },
      { frame: 158, scale: 1.08, x: -18, y: -8 },
    ],
    cursor: [
      { frame: 0, x: 1070, y: 610, visible: false },
      { frame: 158, x: 1070, y: 610, visible: false },
    ],
    callouts: [
      { id: "title-path", frame: 18, endFrame: 150, number: 1, label: "Account → class → post", x: 88, y: 560 },
    ],
  },
  {
    id: "signup",
    title: "Sign up and verify",
    durationInFrames: 449,
    narrationDurationInFrames: 425,
    narration: "Choose Sign Up. Enter your name, school email, a strong password, and choose Student. Confirm your password, then select Sign Up. Open the verification email and select Verify Email before you sign in.",
    captureAsset: "captures/signup-filled.jpg",
    alternateCaptureAsset: "captures/verification-success.jpg",
    alternateAtFrame: 360,
    audioAsset: "audio/signup.mp3",
    camera: [
      { frame: 0, scale: 1.04, x: 0, y: 4 },
      { frame: 250, scale: 1.16, x: 175, y: -18 },
      { frame: 338, scale: 1.18, x: 185, y: -24 },
      { frame: 370, scale: 1.06, x: 38, y: -12 },
      { frame: 448, scale: 1.04, x: 0, y: 0 },
    ],
    cursor: [
      { frame: 35, x: 904, y: 287, visible: true },
      { frame: 280, x: 900, y: 555, visible: true },
      { frame: 320, x: 815, y: 660, visible: true },
      {
        frame: 338,
        x: 815,
        y: 660,
        visible: true,
        click: true,
        target: {
          label: "Sign Up",
          space: "composition",
          bounds: { left: 582, top: 650, right: 1068, bottom: 680 },
        },
      },
      { frame: 351, x: 815, y: 615, visible: false },
      { frame: 448, x: 815, y: 615, visible: false },
    ],
    callouts: [
      { id: "signup-fields", frame: 35, endFrame: 228, number: 1, label: "Use your school details", x: 52, y: 108 },
      { id: "signup-role", frame: 190, endFrame: 330, number: 2, label: "Choose Student", x: 52, y: 220 },
      { id: "signup-submit", frame: 295, endFrame: 354, number: 3, label: "Confirm, then Sign Up", x: 52, y: 332 },
      { id: "signup-verify", frame: 374, endFrame: 442, number: 4, label: "Verify your school email", x: 52, y: 444 },
    ],
  },
  {
    id: "signin",
    title: "Verify and sign in",
    durationInFrames: 194,
    narrationDurationInFrames: 170,
    narration: "After verification, choose Sign In. Enter the same email and password to open your Student Hub.",
    captureAsset: "captures/verification-success.jpg",
    alternateCaptureAsset: "captures/signin-filled.jpg",
    alternateAtFrame: 69,
    audioAsset: "audio/signin.mp3",
    camera: [
      { frame: 0, scale: 1.04, x: 0, y: 0 },
      { frame: 34, scale: 1.08, x: 0, y: -8 },
      { frame: 58, scale: 1.04, x: 0, y: 0 },
      { frame: 79, scale: 1.04, x: 0, y: 0 },
      { frame: 193, scale: 1.16, x: 170, y: -50 },
    ],
    cursor: [
      { frame: 0, x: 637, y: 365, visible: true },
      {
        frame: 22,
        x: 637,
        y: 365,
        visible: true,
        click: true,
        target: {
          label: "Verification Sign In",
          space: "composition",
          bounds: { left: 421, top: 344, right: 858, bottom: 387 },
        },
      },
      { frame: 50, x: 637, y: 365, visible: false },
      { frame: 85, x: 915, y: 412, visible: true },
      { frame: 143, x: 760, y: 345, visible: true },
      {
        frame: 161,
        x: 760,
        y: 400,
        visible: true,
        click: true,
        target: {
          label: "Sign In",
          space: "composition",
          bounds: { left: 584, top: 379, right: 941, bottom: 435 },
        },
      },
      { frame: 190, x: 760, y: 400, visible: false },
    ],
    callouts: [
      { id: "verification-complete", frame: 4, endFrame: 58, number: 1, label: "Email verified", x: 60, y: 128 },
      { id: "same-credentials", frame: 82, endFrame: 188, number: 2, label: "Use the same credentials", x: 60, y: 252 },
    ],
  },
  {
    id: "join-class",
    title: "Join a class",
    durationInFrames: 222,
    narrationDurationInFrames: 198,
    narration: "Select Join Class. Type the six-character code from your teacher, then choose Join Class again.",
    captureAsset: "captures/student-hub-empty.jpg",
    alternateCaptureAsset: "captures/join-class-code.jpg",
    alternateAtFrame: 69,
    captureObjectPosition: "center top",
    alternateCaptureObjectPosition: "center",
    audioAsset: "audio/join-class.mp3",
    camera: [
      { frame: 0, scale: 1.02, x: 0, y: 0 },
      { frame: 58, scale: 1.02, x: 0, y: 0 },
      { frame: 79, scale: 1.12, x: 2, y: 10 },
      { frame: 105, scale: 1.22, x: 4, y: 18 },
      { frame: 221, scale: 1.16, x: 4, y: 10 },
    ],
    cursor: [
      { frame: 0, x: 1165, y: 197, visible: true },
      {
        frame: 16,
        x: 1165,
        y: 197,
        visible: true,
        click: true,
        target: {
          label: "Open Join Class",
          space: "composition",
          bounds: { left: 1125, top: 189, right: 1222, bottom: 223 },
        },
      },
      { frame: 52, x: 1165, y: 197, visible: false },
      { frame: 84, x: 722, y: 436, visible: true },
      { frame: 155, x: 775, y: 468, visible: true },
      {
        frame: 175,
        x: 775,
        y: 468,
        visible: true,
        click: true,
        target: {
          label: "Submit Join Class",
          space: "composition",
          bounds: { left: 742, top: 460, right: 841, bottom: 499 },
        },
      },
      { frame: 215, x: 775, y: 468, visible: false },
    ],
    callouts: [
      { id: "join-open", frame: 4, endFrame: 55, number: 1, label: "Select Join Class", x: 58, y: 110 },
      { id: "join-code", frame: 74, endFrame: 158, number: 2, label: "Enter the 6-character code", x: 58, y: 222 },
      { id: "join-submit", frame: 145, endFrame: 214, number: 3, label: "Join the class", x: 58, y: 334 },
    ],
  },
  {
    id: "enter-class",
    title: "Enter the class",
    durationInFrames: 147,
    narrationDurationInFrames: 123,
    narration: "Open the class card to see announcements, assignments, and posts.",
    captureAsset: "captures/student-hub.jpg",
    alternateCaptureAsset: "captures/class-feed.jpg",
    alternateAtFrame: 60,
    audioAsset: "audio/enter-class.mp3",
    camera: [
      { frame: 0, scale: 1.04, x: 0, y: 0 },
      { frame: 44, scale: 1.18, x: -80, y: -24 },
      { frame: 70, scale: 1.02, x: 0, y: 0 },
      { frame: 146, scale: 1.09, x: 2, y: -20 },
    ],
    cursor: [
      { frame: 0, x: 330, y: 170, visible: true },
      {
        frame: 32,
        x: 330,
        y: 170,
        visible: true,
        click: true,
        target: {
          label: "English 10 Reading Circle class card",
          space: "composition",
          bounds: { left: 197, top: 115, right: 527, bottom: 273 },
        },
      },
      { frame: 72, x: 890, y: 312, visible: true },
      { frame: 140, x: 890, y: 312, visible: false },
    ],
    callouts: [
      { id: "class-card", frame: 8, endFrame: 50, number: 1, label: "Open the class card", x: 58, y: 118 },
      { id: "class-space", frame: 72, endFrame: 140, number: 2, label: "Your class workspace", x: 58, y: 238 },
    ],
  },
  {
    id: "open-post",
    title: "Open a new post",
    durationInFrames: 99,
    narrationDurationInFrames: 75,
    narration: "Select Create New Post.",
    captureAsset: "captures/class-feed.jpg",
    alternateCaptureAsset: "captures/post-composer.jpg",
    alternateAtFrame: 46,
    audioAsset: "audio/open-post.mp3",
    camera: [
      { frame: 0, scale: 1.04, x: 0, y: 0 },
      { frame: 35, scale: 1.19, x: -160, y: 40 },
      { frame: 45, scale: 1.12, x: -80, y: 40 },
      { frame: 56, scale: 1.02, x: 0, y: 0 },
      { frame: 98, scale: 1.11, x: 0, y: -25 },
    ],
    cursor: [
      { frame: 6, x: 1145, y: 202, visible: true },
      { frame: 22, x: 1000, y: 135, visible: true },
      {
        frame: 35,
        x: 1000,
        y: 135,
        visible: true,
        click: true,
        target: {
          label: "Create New Post",
          space: "composition",
          bounds: { left: 943, top: 116, right: 1100, bottom: 158 },
        },
      },
      { frame: 72, x: 740, y: 250, visible: true },
      { frame: 96, x: 740, y: 250, visible: false },
    ],
    callouts: [
      { id: "create-post", frame: 4, endFrame: 44, number: 1, label: "Create New Post", x: 58, y: 125 },
      { id: "composer-ready", frame: 60, endFrame: 94, number: 2, label: "Composer ready", x: 58, y: 245 },
    ],
  },
  {
    id: "compose",
    title: "Write and format",
    durationInFrames: 350,
    narrationDurationInFrames: 326,
    narration: "Add a clear title and write your response. Select text and choose Bold. Then choose a highlight color. The editor previews exactly what classmates and teachers will see.",
    captureAsset: "captures/post-written.jpg",
    captureTimeline: [
      { frame: 0, asset: "captures/post-written.jpg" },
      { frame: 210, asset: "captures/post-bold.jpg" },
      { frame: 285, asset: "captures/post-highlight-palette.jpg" },
      { frame: 313, asset: "captures/post-formatted.jpg" },
    ],
    audioAsset: "audio/compose.mp3",
    camera: [
      { frame: 0, scale: 1.02, x: 0, y: 0 },
      { frame: 100, scale: 1.16, x: 0, y: -95 },
      { frame: 160, scale: 1.19, x: 6, y: -70 },
      { frame: 180, scale: 1.10, x: 0, y: -45 },
      { frame: 323, scale: 1.12, x: 0, y: -44 },
      { frame: 349, scale: 1.15, x: 0, y: -42 },
    ],
    cursor: [
      { frame: 35, x: 714, y: 286, visible: true },
      { frame: 100, x: 642, y: 485, visible: true },
      { frame: 180, x: 670, y: 265, visible: true },
      {
        frame: 200,
        x: 670,
        y: 265,
        visible: true,
        click: true,
        target: {
          label: "Bold",
          space: "composition",
          bounds: { left: 659, top: 258, right: 693, bottom: 293 },
        },
      },
      { frame: 250, x: 625, y: 265, visible: true },
      {
        frame: 275,
        x: 625,
        y: 265,
        visible: true,
        click: true,
        target: {
          label: "Open Highlight palette",
          space: "composition",
          bounds: { left: 615, top: 258, right: 651, bottom: 293 },
        },
      },
      {
        frame: 303,
        x: 673,
        y: 348,
        visible: true,
        click: true,
        target: {
          label: "Amber #fef3c7",
          space: "composition",
          bounds: { left: 660, top: 335, right: 690, bottom: 363 },
        },
      },
      { frame: 335, x: 673, y: 348, visible: false },
    ],
    callouts: [
      { id: "clear-title", frame: 12, endFrame: 92, number: 1, label: "Add a clear title", x: 46, y: 104 },
      { id: "write-response", frame: 72, endFrame: 175, number: 2, label: "Write your response", x: 46, y: 216 },
      { id: "bold", frame: 165, endFrame: 244, number: 3, label: "Select text → Bold", x: 46, y: 328 },
      { id: "highlight", frame: 242, endFrame: 342, number: 4, label: "Choose amber Highlight", x: 46, y: 440 },
    ],
  },
  {
    id: "publish",
    title: "Publish",
    durationInFrames: 113,
    narrationDurationInFrames: 89,
    narration: "Review your work, then select Publish.",
    captureAsset: "captures/publish-action.jpg",
    captureObjectPosition: "center bottom",
    audioAsset: "audio/publish.mp3",
    camera: [
      { frame: 0, scale: 1.04, x: 0, y: -12 },
      { frame: 48, scale: 1.19, x: -90, y: -120 },
      { frame: 82, scale: 1.19, x: -90, y: -120 },
      { frame: 112, scale: 1.15, x: -82, y: -108 },
    ],
    cursor: [
      { frame: 12, x: 1080, y: 670, visible: true },
      { frame: 48, x: 915, y: 515, visible: true },
      {
        frame: 69,
        x: 915,
        y: 515,
        visible: true,
        click: true,
        target: {
          label: "Publish",
          space: "composition",
          bounds: { left: 875, top: 508, right: 973, bottom: 548 },
        },
      },
      { frame: 100, x: 1080, y: 670, visible: false },
    ],
    callouts: [
      { id: "review", frame: 8, endFrame: 53, number: 1, label: "Review your work", x: 58, y: 150 },
      { id: "publish-action", frame: 46, endFrame: 106, number: 2, label: "Select Publish", x: 58, y: 268 },
    ],
  },
  {
    id: "verify",
    title: "Verify and finish",
    durationInFrames: 158,
    narrationDurationInFrames: 134,
    narration: "Your post appears in the class feed with bold and highlighting preserved. You're ready to write on LitBlog.",
    captureAsset: "captures/published-post.jpg",
    audioAsset: "audio/verify.mp3",
    camera: [
      { frame: 0, scale: 1.03, x: 0, y: 0 },
      { frame: 157, scale: 1.13, x: 0, y: -34 },
    ],
    cursor: [
      { frame: 0, x: 880, y: 450, visible: false },
      { frame: 157, x: 880, y: 450, visible: false },
    ],
    callouts: [
      { id: "format-preserved", frame: 10, endFrame: 112, number: 1, label: "Bold + highlight preserved", x: 54, y: 132 },
      { id: "ready", frame: 54, endFrame: 152, number: 2, label: "Ready to write", x: 54, y: 246 },
    ],
  },
];

let nextStartFrame = 0;

export const SCENES = Object.freeze(rawScenes.map((scene) => {
  const startFrame = nextStartFrame;
  nextStartFrame += scene.durationInFrames;
  return Object.freeze({
    ...scene,
    startFrame,
    caption: Object.freeze({
      startOffsetFrames: CAPTION_INSET_FRAMES,
      endOffsetFrames: scene.durationInFrames - CAPTION_INSET_FRAMES,
      text: scene.narration,
    }),
  });
}));

export const VIDEO = Object.freeze({
  id: "LitBlogsTutorial",
  width: 1280,
  height: 720,
  fps: FPS,
  durationInFrames: nextStartFrame,
  durationInSeconds: nextStartFrame / FPS,
});

export const SCENE_BY_ID = Object.freeze(Object.fromEntries(
  SCENES.map((scene) => [scene.id, scene]),
));
